### sklearn.preprocessing.PolynomialFeatures
* class sklearn.preprocessing.PolynomialFeatures(degree=2, *, interaction_only=False, include_bias=True, order='C')

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# 다항식으로 변환된 다항식
X=np.arange(4).reshape(2,2)
print('일차 단항식 계수 feature: \n', X)

poly = PolynomialFeatures(degree=2)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 계수 feature: \n', poly_ftr)

일차 단항식 계수 feature: 
 [[0 1]
 [2 3]]
변환된 2차 다항식 계수 feature: 
 [[1. 0. 1. 0. 0. 1.]
 [1. 2. 3. 4. 6. 9.]]


In [3]:
def polynomial_func(X):
    y = 1+2*X+ X**2+X**3
    return y

result = polynomial_func(X)
result

array([[ 1,  5],
       [17, 43]])

In [4]:
poly = PolynomialFeatures(degree=3 )
poly_ftr = poly.fit_transform(X)

In [5]:
poly_ftr

array([[ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [6]:
poly_ftr.shape

(2, 10)

In [7]:
result.shape

(2, 2)

In [11]:
import pandas as pd
from sklearn.pipeline import Pipeline as pipeline
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
from sklearn.metrics import * 
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df = pd.read_csv('./datasets/housing.csv', header=None, delimiter=r"\s+", names=column_names)

y_target = df['MEDV']
X_data = df.drop(['MEDV'], axis=1, inplace=False)

X_train, X_test, y_train, y_test = train_test_split(X_data, y_target, test_size =0.3, random_state=156)

# pipeline으로 poly 변경
p_model = pipeline([('poly', PolynomialFeatures(degree=2, include_bias = False)), ('linear', LinearRegression())])
p_model

p_model.fit(X_train, y_train)
y_preds = p_model.predict(X_test)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print('MSE : {0:.3f}, RMSE : {1:.3F}'.format(mse, rmse))
print('Variance score : {0:.3f}'.format(r2_score(y_test, y_preds)))

X_train_poly = PolynomialFeatures(degree=2, include_bias = False).fit_transform(X_train, y_train)
print(X_train_poly.shape, X_train.shape)

MSE : 15.556, RMSE : 3.944
Variance score : 0.782
(354, 104) (354, 13)


In [12]:
# pipeline으로 poly 변경
p_model = pipeline([('poly', PolynomialFeatures(degree=3, include_bias = False)), ('linear', LinearRegression())])
p_model

p_model.fit(X_train, y_train)
y_preds = p_model.predict(X_test)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)

print('MSE : {0:.3f}, RMSE : {1:.3F}'.format(mse, rmse))
print('Variance score : {0:.3f}'.format(r2_score(y_test, y_preds)))

X_train_poly = PolynomialFeatures(degree=2, include_bias = False).fit_transform(X_train, y_train)
print(X_train_poly.shape, X_train.shape)

MSE : 79625.592, RMSE : 282.180
Variance score : -1116.598
(354, 104) (354, 13)
